name: macOS
on:
  push:
    branches:
      - stable
  workflow_dispatch:
  
jobs:
  macOS_x86-64:
    runs-on: macos-13

    steps:
      - name: Install brew packages
        run: |
          brew install dos2unix

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Python
        run: |
          wget https://www.python.org/ftp/python/3.9.7/python-3.9.7-macosx10.9.pkg
          echo "f40f7407d20f88a6a64678b6586853de16cc5d7d07c82a8a2a7e43bba59dbae5 *python-3.9.7-macosx10.9.pkg" > SHA256SUMS
          shasum -c SHA256SUMS

      - name: Install Python
        run: |
          sudo installer -pkg python-3.9.7-macosx10.9.pkg -target /

      - name: Add Python to PATH
        run: |
          echo /Library/Frameworks/Python.framework/Versions/3.9/bin >> $GITHUB_PATH

      - name: Install pip and pipenv
        run: |
          python3 -m pip install pip==21.3.1 pipenv==2021.5.29

      - name: Install appdmg
        run: |
          npm install -g appdmg

      - name: Run pipenv sync --dev
        run: |
          pipenv sync --dev

      - name: Update version
        run: |
          fsbuild/version

      - name: Bootstrap
        if: hashFiles('fsbuild/bootstrap') != ''
        run: |
          fsbuild/bootstrap

      - name: Configure
        if: hashFiles('fsbuild/configure') != ''
        run: |
          fsbuild/configure

      - name: Build
        run: |
          pipenv run fsbuild/build

      - name: Bundle
        run: |
          fsbuild/bundle

      - name: Archive
        run: |
          fsbuild/archive

      - uses: actions/upload-artifact@v2
        with:
          name: macOS_x86-64
          path: fsbuild/_dist/*

