name: Source

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version to set in tarballs'
        required: false
        default: '0.0.0-edge'
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version to set in tarballs'
        required: false
        default: '0.0.0-edge'

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  Source:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: 3.12

      - name: Set base version
        run: |
          echo "BASEVERSION_FS=${{ inputs.version }}" > BASEVERSION.FS
        if: ${{ inputs.version }}

      - name: Update version
        run: |
          fsbuild/version --update

      - name: Bootstrap
        if: hashFiles('fsbuild/bootstrap') != ''
        run: |
          fsbuild/bootstrap

      - name: Configure
        if: hashFiles('fsbuild/configure') != ''
        run: |
          fsbuild/configure

      - name: Source
        run: |
          fsbuild/source

      - name: Upload builds to artifact storage
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: Source-${{ inputs.version }}
          path: fsbuild/_dist/*
        if: github.event_name != 'pull_request'
