name: Source

on:
  push:
    branches:
      - master
      - beta
      - stable
  pull_request:
    branches:
      - master
      - beta
      - stable

jobs:
  Source:
    runs-on: ubuntu-18.04

    env:
      UPLOAD_ENABLED: ${{ secrets.DROPBOX_ACCESS_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Log environment
        run: |
          env

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Update version
        run: |
          fsbuild/version --update

      - name: Bootstrap
        if: hashFiles('fsbuild/bootstrap') != ''
        run: |
          fsbuild/bootstrap

      - name: Configure
        if: hashFiles('fsbuild/configure') != ''
        run: |
          fsbuild/configure

      - name: Source
        run: |
          fsbuild/source

      - name: Upload builds to artifact storage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Source
          path: fsbuild/_dist/*

      - name: Upload build to Dropbox folder
        if: >-
          env.UPLOAD_ENABLED != null && (
            github.ref == 'refs/heads/master' ||
            github.ref == 'refs/heads/dev' ||
            github.ref == 'refs/heads/beta' ||
            github.ref == 'refs/heads/stable'
          )
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        run: |
          python3 -m pip install dropbox==11.23.0
          fsbuild/upload
