name: Source

on:
  push:
    branches:
      - stable
  workflow_dispatch:

jobs:
  Source:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log environment
        run: |
          env

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Update version
        run: |
          fsbuild/version --update

      - name: Bootstrap
        if: hashFiles('fsbuild/bootstrap') != ''
        run: |
          fsbuild/bootstrap

      - name: Configure
        if: hashFiles('fsbuild/configure') != ''
        run: |
          fsbuild/configure

      - name: Source
        run: |
          fsbuild/source

      - uses: actions/upload-artifact@v2
        with:
          name: Source
          path: fsbuild/_dist/*
